export enum LawyerSpecialty {
  ADMINISTRATIVO = "Direito Administrativo",
AMBIENTAL = "Direito Ambiental",
BANCARIO = "Direito Bancário",
CIVIL = "Direito Civil",
COMERCIAL = "Direito Comercial",
CONSTITUCIONAL = "Direito Constitucional",
CONSUMIDOR = "Direito do Consumidor",
CRIMINAL = "Direito Criminal",
ELEITORAL = "Direito Eleitoral",
EMPRESARIAL = "Direito Empresarial",
FAMILIA = "Direito de Família",
IMOBILIARIO = "Direito Imobiliário",
INTERNACIONAL = "Direito Internacional",
PREVIDENCIARIO = "Direito Previdenciário",
SUCESSOES = "Direito das Sucessões",
TRABALHO = "Direito do Trabalho",
TRIBUTARIO = "Direito Tributário",
DESPORTIVO = "Direito Desportivo",
EDUCACIONAL = "Direito Educacional",
ENERGIA = "Direito de Energia",
ENTRETENIMENTO = "Direito do Entretenimento",
HOSPITALAR = "Direito Hospitalar",
IMPRENSA = "Direito de Imprensa",
INFORMATICA = "Direito da Informática",
MARCAS_PATENTES = "Direito de Marcas e Patentes",
MEDICO = "Direito Médico",
MILITAR = "Direito Militar",
PETROLEO_GAS = "Direito de Petróleo e Gás",
PROCESSUAL_CIVIL = "Direito Processual Civil",
PROCESSUAL_PENAL = "Direito Processual Penal",
PROPRIEDADE_INTELECTUAL = "Propriedade Intelectual",
SAUDE = "Direito da Saúde",
SEGUROS = "Direito de Seguros",
SOCIETARIO = "Direito Societário",
TERCEIRO_SETOR = "Direito do Terceiro Setor",
URBANISTICO = "Direito Urbanístico",
AERONAUTICO = "Direito Aeronáutico",
AGRARIO = "Direito Agrário",
AUTORAL = "Direito Autoral",
BIODIREITO = "Biodireito",
COMPLIANCE = "Compliance",
CONCORRENCIAL = "Direito Concorrencial",
DIGITAL = "Direito Digital",
FALIMENTAR = "Direito Falimentar",
MARITIMO = "Direito Marítimo",
MINERARIO = "Direito Minerário",
REGULATORIO = "Direito Regulatório"
}

export const lawyerSpecialties = Object.entries(LawyerSpecialty).map(
  ([key, value]) => ({
    value: LawyerSpecialty[key as keyof typeof LawyerSpecialty],
    label: value,
  }),
);
